### ISSUE TITLE
scheduleOnceIn with delta == 0

### ISSUE THREAD

**Issue by Vance-Turner** [eclab/mason#10]
If a delta of zero is passed to scheduleOnceIn, it appears the ordering is not respected. From looking around in the Schedule class it seems this makes sense, but the documentation doesn't suggest this behavior. Is this what is expected?

My use case is a Steppable (call it **A**) that accepts a Function object that returns True/False. If True, we kill the sim. If False, we schedule **A** to run again with priority MAX_INTEGER.

Assume we use **A** with a function that returns True if the current time is greater than some given time and when the function returns False, we schedule to run again after 24.0 units of time. Assume we have it scheduled to run at 48.0

The issue I have is that another Steppable is scheduled to run at time 48.0. When that Steppable runs, it schedules another Steppable to run at time 48.0 but with ordering 0.

That final Steppable never runs because **A** kills the simulation even though it was scheduled with max ordering. Is this expected?

**Comment by eclab** [comment]
When the schedule advances to timestep T, it grabs *all* the events scheduled at that timestep, then sorts them by ordering, then executes all of them.  MASON isn't designed to support reinserting at the same timestep: this could lead to queue starvation.

That _scheduleOnce() is permitting this is a bug, I'm afraid.  Fixing it will break your code but we have to do it, otherwise bad things could happen.

**Comment by eclab** [comment]
Actually the way things currently work is: if you insert at the current timestep, MASON will instead insert at the current timestep + epsilon, where epsilon is the smallest possible time slice. So you shouldn't be *able* to insert at the same timestep.  However the code may not be working properly, I'll tweak it.
